### ISSUE TITLE
Send in ratings.

### ISSUE THREAD

**Issue by marcelhollerbach** [coolcrowd/worker-service#17]
0:14:51.512 [ratpack-compute-1-2] ERROR edu.kit.ipd.crowdcontrol.workerservice.ErrorHandler - an internal error occurred
atpack.render.NoSuchRendererException: No renderer for object '201' of type 'class java.lang.Integer'
       at ratpack.render.internal.DefaultRenderController.doRender(DefaultRenderController.java:76)
       at ratpack.render.internal.DefaultRenderController.doRender(DefaultRenderController.java:58)
       at ratpack.render.internal.DefaultRenderController.render(DefaultRenderController.java:43)
       at ratpack.handling.internal.DefaultContext.render(DefaultContext.java:304)
       at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:42)
       at ratpack.exec.Promise.lambda$null$9(Promise.java:304)
       at ratpack.exec.Downstream$1.success(Downstream.java:73)
       at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:42)
       at ratpack.exec.Downstream$2.success(Downstream.java:104)
       at ratpack.exec.internal.DefaultExecution$2.lambda$success$1(DefaultExecution.java:161)
       at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:419)
       at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:246)
       at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:240)
       at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:220)
       at ratpack.exec.internal.DefaultExecution.access$100(DefaultExecution.java:45)
       at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.resume(DefaultExecution.java:452)
       at ratpack.exec.internal.DefaultExecution$2.success(DefaultExecution.java:161)
       at ratpack.exec.Downstream.lambda$accept$0(Downstream.java:192)
       at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
       at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
       at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:258)
       at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
       at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:113)
       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
       at java.lang.Thread.run(Thread.java:745)
0:14:51.515 [ratpack-compute-1-3] ERROR edu.kit.ipd.crowdcontrol.workerservice.ErrorHandler - an internal error occurred
atpack.render.NoSuchRendererException: No renderer for object '201' of type 'class java.lang.Integer'
       at ratpack.render.internal.DefaultRenderController.doRender(DefaultRenderController.java:76)
       at ratpack.render.internal.DefaultRenderController.doRender(DefaultRenderController.java:58)
       at ratpack.render.internal.DefaultRenderController.render(DefaultRenderController.java:43)
       at ratpack.handling.internal.DefaultContext.render(DefaultContext.java:304)
       at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:42)
       at ratpack.exec.Promise.lambda$null$9(Promise.java:304)
       at ratpack.exec.Downstream$1.success(Downstream.java:73)
       at ratpack.exec.internal.DefaultPromise$1.success(DefaultPromise.java:42)
       at ratpack.exec.Downstream$2.success(Downstream.java:104)
       at ratpack.exec.internal.DefaultExecution$2.lambda$success$1(DefaultExecution.java:161)
       at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.exec(DefaultExecution.java:419)
       at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:246)
       at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:240)
       at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:220)
       at ratpack.exec.internal.DefaultExecution.access$100(DefaultExecution.java:45)
       at ratpack.exec.internal.DefaultExecution$SingleEventExecStream.resume(DefaultExecution.java:452)
       at ratpack.exec.internal.DefaultExecution$2.success(DefaultExecution.java:161)
       at ratpack.exec.Downstream.lambda$accept$0(Downstream.java:192)
       at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
       at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
       at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:258)
       at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
       at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:113)
       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
       at java.lang.Thread.run(Thread.java:745)

**Comment by marcelhollerbach** [comment]
java.util.concurrent.CompletionException: edu.kit.ipd.crowdcontrol.workerservice.InternalServerErrorException: Cause: Object service responded with: Error! Answer without valid ratings. In class edu.kit.ipd.crowd
control.objectservice.quality.ratingQuality.RatingQualityByDistribution
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at edu.kit.ipd.crowdcontrol.workerservice.objectservice.Communication$1.completed(Communication.java:281)
        at com.mashape.unirest.http.HttpClientHelper$1.completed(HttpClientHelper.java:82)
        at com.mashape.unirest.http.HttpClientHelper$1.completed(HttpClientHelper.java:75)
        at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:115)
        at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:173)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:355)
        at org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:242)
        at org.apache.http.impl.nio.client.LoggingAsyncRequestExecutor.inputReady(LoggingAsyncRequestExecutor.java:87)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:264)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:73)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:37)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:113)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:584)
        at java.lang.Thread.run(Thread.java:745)
Caused by: edu.kit.ipd.crowdcontrol.workerservice.InternalServerErrorException: Cause: Object service responded with: Error! Answer without valid ratings. In class edu.kit.ipd.crowdcontrol.objectservice.quality.r
atingQuality.RatingQualityByDistribution
        at edu.kit.ipd.crowdcontrol.workerservice.objectservice.Communication.throwOr(Communication.java:257)
        at edu.kit.ipd.crowdcontrol.workerservice.objectservice.Communication.lambda$submitRating$12(Communication.java:165)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 22 common frames omitted

^^ forgot this one.

**Comment by LeanderK** [comment]
thx, that one should be easy

**Comment by marcelhollerbach** [comment]
awesome.
