### ISSUE TITLE
Calibrations Submit

### ISSUE THREAD

**Issue by kelunik** [coolcrowd/worker-service#30]
This happens only if the calibration is the one that's accepted. If it's a non-accepted, if succeeds with `FINISHED`.

![Part 1](http://i.imgur.com/wIsTCcE.png)
![Part 2](http://i.imgur.com/1H1IZd1.png)

relevant log: https://gist.github.com/kelunik/dbdcacab597f4b5a511e

**Comment by LeanderK** [comment]
this happened when a worker tried to submit a rating, i think it was the next call.

**Comment by kelunik** [comment]
There's a title: _Calibration Submit_.

**Comment by LeanderK** [comment]
https://gist.github.com/kelunik/dbdcacab597f4b5a511e

**Comment by marcelhollerbach** [comment]
```
workerservice_1 | org.jooq.exception.DataAccessException: SQL [select `crowdcontrol`.`Answer`.`id_answer`, `crowdcontrol`.`Answer`.`experiment`, `crowdcontrol`.`Answer`.`answer`, `crowdcontrol`.`Answer`.`timestam
p`, `crowdcontrol`.`Answer`.`worker_id`, `crowdcontrol`.`Answer`.`reservation`, `crowdcontrol`.`Answer`.`quality`, `crowdcontrol`.`Answer`.`quality_assured`, `crowdcontrol`.`Answer`.`system_response`, `crowdcontr
ol`.`Answer`.`hash`, count(`crowdcontrol`.`Rating`.`id_rating`) as `count` from `crowdcontrol`.`Answer` left outer join `crowdcontrol`.`Rating` on (`crowdcontrol`.`Rating`.`answer_r` = `crowdcontrol`.`Answer`.`id
_answer` and (`crowdcontrol`.`Rating`.`rating` is not null or `crowdcontrol`.`Rating`.`timestamp` >= ?)) where (`crowdcontrol`.`Answer`.`worker_id` <> ? and `crowdcontrol`.`Answer`.`experiment` = ?)]; In aggregat
ed query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'crowdcontrol.Answer.id_answer'; this is incompatible with sql_mode=only_full_group_by
workerservice_1 |       at org.jooq.impl.Tools.translate(Tools.java:1690)
workerservice_1 |       at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:660)
workerservice_1 |       at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
workerservice_1 |       at org.jooq.impl.AbstractResultQuery.fetch(AbstractResultQuery.java:305)
workerservice_1 |       at org.jooq.impl.SelectImpl.fetch(SelectImpl.java:2577)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.database.operations.ExperimentsPlatformOperations.getOtherAnswersWithCount(ExperimentsPlatformOperations.java:290)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.TaskChooserAlgorithm.constructRatingView(TaskChooserAlgorithm.java:145)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.TaskChooserAlgorithm.constructView(TaskChooserAlgorithm.java:105)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.AntiSpoof.next(AntiSpoof.java:117)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.Queries.lambda$getStrategyStep$6(Queries.java:311)
workerservice_1 |       at java.util.Optional.flatMap(Optional.java:241)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.Queries.getStrategyStep(Queries.java:311)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.Queries.getNext(Queries.java:156)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.query.Queries.getNext(Queries.java:123)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.RatpackRouter.lambda$null$3(RatpackRouter.java:78)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:256)
workerservice_1 |       at ratpack.handling.internal.MethodHandler.handle(MethodHandler.java:44)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:256)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.insert(DefaultContext.java:278)
workerservice_1 |       at ratpack.path.internal.PathHandler.handle(PathHandler.java:61)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:256)
workerservice_1 |       at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:256)
workerservice_1 |       at ratpack.path.internal.PathHandler.handle(PathHandler.java:63)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:256)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:269)
workerservice_1 |       at edu.kit.ipd.crowdcontrol.workerservice.RatpackRouter.lambda$null$0(RatpackRouter.java:67)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.next(DefaultContext.java:256)
workerservice_1 |       at ratpack.handling.internal.DefaultContext.lambda$start$4(DefaultContext.java:181)
workerservice_1 |       at ratpack.exec.internal.DefaultExecution$InitialExecStream.exec(DefaultExecution.java:379)
workerservice_1 |       at ratpack.exec.internal.DefaultExecution.exec(DefaultExecution.java:246)
workerservice_1 |       at ratpack.exec.internal.DefaultExecution.intercept(DefaultExecution.java:240)
workerservice_1 |       at ratpack.exec.internal.DefaultExecution.drain(DefaultExecution.java:220)
workerservice_1 |       at ratpack.exec.internal.DefaultExecution.<init>(DefaultExecution.java:96)
workerservice_1 |       at ratpack.exec.internal.DefaultExecController$1.lambda$start$0(DefaultExecController.java:172)
workerservice_1 |       at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
workerservice_1 |       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
workerservice_1 |       at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:258)
workerservice_1 |       at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
workerservice_1 |       at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$0(DefaultExecController.java:113)
workerservice_1 |       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
workerservice_1 |       at java.lang.Thread.run(Thread.java:745)

```
